openapi: 3.0.3
info:
  title: Flowagent V3 – GDrive Writer
  version: "1.0.0"
  description: |
    Endpoint per ricevere e salvare un file JSON nel repository sincronizzato con Google Drive.
    Usato dal GPT Flowagent Research per scrivere il file di recap con i dati raccolti.

servers:
  - url: https://flowagent-v3-gdrive-sync.onrender.com
    description: Render deploy – Flowagent GDrive Write

paths:
  /write:
    post:
      operationId: driveWrite
      summary: Salva un file JSON su Google Drive nella cartella /5_Resources_Internal/Company_Person_Research_from_layer/
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - path
                - content
              properties:
                path:
                  type: string
                  description: Percorso relativo in Drive (es. "5_Resources_Internal/Company_Person_Research_from_layer/maiora-spa_20251031.json")
                content:
                  type: object
                  description: Contenuto JSON completo da salvare
                overwrite:
                  type: boolean
                  default: true
      responses:
        '200':
          description: File salvato correttamente
        '400':
          description: Errore nel payload
        '500':
          description: Errore del server
