services:
  - type: web
    name: flowagent-v3-gdrive-sync
    plan: free
    region: frankfurt
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_FOLDER_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: POLL_SECONDS
        sync: false
      - key: BEARER_TOKEN
        sync: false
      - key: OCR_ENABLED
        value: "1"
      - key: GOOGLE_SHEET_ID
        value: 1hQdePhFouPcOSxkd_OPdvhnlVEZbnciq32reSKXvowg
        sync: false
      - key: GOOGLE_SHEET_NAME
        value: Foglio1
        sync: false
      - key: GSHEET_CREDS_JSON
        value: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZmxvd2FnZW50LXYzLXN5bmMiLAogICJwcml2YXRlX2tleV9pZCI6ICI0MDgxNzkwYTU5ODhlZjQxN2IyOTlmOGE0NTg3OWEzOTczZWFhMmNjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUMwMDZsTEdwNUxvMFlQXG51c0RwUitPd2UvQmVFaXhId2VLVXptVEJWVFVNOEViV201alJ3Sm5lTERoaW8zVEVrcVhNOHhna0ZzR1oyZVlRXG45SldvVHhmRElRN1RtOVI3Rnc1TEhLZ0hwYXRtc0tCWlpNSWFuK1RialVYam5pQ3p2TXVBSHVyYTlXVVNyazRwXG53dzJiaFBZeHVnWDVEZ1lLSE16ZzFxM3NiTFFZVWMvUGV4a2prQ0J6RlBPd3pDeUVlN2g2WE1BNnZpL21pbXZtXG42eHowMzBENGJ4YTNIS3VJMGhsUFB1MVJJa292R0poVFlOVjlmaWJTVU14WVZqdjFDVFo4RFUrL3J1U0t0RTl3XG5Ob05MbVNSdUppbklnRFZlTDV5dXFJSStyamxIaUhLVUU4eGUzUkR5Qmx4bGI4bi84UUJVT1VVQmJ1UExKN21TXG5vWlZmaE05N0FnTUJBQUVDZ2dFQUM5NUVpYWhpbDcvbU94amNtYk1RYVVCV0EyYVpqRGFMVDQxaDhZcUFWeEoxXG5WdjNHTTcrNm1aeWZaR0gzUTJocjBRUnF2SnVrSm9KUFRMMzlwd0ZWSTdwOHVOV1pyTWFHMFFrOWRVRnVsTFZ6XG5iWmRreUdpU2xjV1p2dWFRbmJUK3NMQ2ptRWZTaHdwYTVjVE0renkxYmxUa3NrUE93NnVNcEh4ZmJsbW9INCtYXG5jNHVPVXVWODZjeVh0VkdIbTgweEZJNTczdzZxb25KS0FUSXlzQ0Z1S3gzWHk3dGJ4UFZxb3AzTWx0UWRENkNGXG5rb2xNWHErLzMzY0FzdzFFRFZBcWo4WHovR0FFb29EbmNwUi85K01nbFdIbldvdHl1MXRtZy94TzdSeUhGM1BrXG40Wm1HeGpGemw2MXZGL3FqVGtaTFhtWVRiTTU2b2tZRTNYeHlxTFd5R1FLQmdRRHdadTIxV2IrNEpGNUJrUDVjXG5RV3lWdjljWmhMaXFaUFF5SHFqWm5Hd3YrQVVKR2VNb2NPNTBGZjBtVFg5RldrVmtnUDRpUWk4TzEvazFHNnhtXG4yaVZYSnhvaVdyMjQ5TnlmMVM3blUxdmdJeDhIcm5FQmJYUFQralNrZ0hvdjYyRC84dTlVdlFuZWNsRUpxWlUyXG44dGV3RmdFTHB1U243Y3pEUFZHRmZoTVl2UUtCZ1FEQWp6QjRWNFVTZUJJVTE0bTRZR05xcVlDMXMxWE5iZzd4XG5wUGRLMWpqMkk3VFBVNlIwbHA5VmVJNDdEazdKaFpBekxQTzRuK3MwaTJPTEtmcEVkYld2Rkl3Y1hZQ2RLMXhyXG5uQ3p3d1prd3Nhek42NURWdzBGOHVtMHhuRzVUYkJmYno4UTFYMUloL2xUNEkzWmtreVBEQk9SQ0ZleWZXb1p5XG5xckxvbldXWWx3S0JnRXBYMmswSjJ6TXI5QVljdTd4MTh3bUFVUm13SkpkMUx0dE5CZlI5M2lzYmJSczZhVGc1XG5iRlJ6OUZ4aS9PZkttY2tSNXdWYktFaFQyOXBqbTNZWEloTUlvWmxjTEczRk0zRXVNUm9TZWtnZk5GcGd4TXVuXG5PSG1tVjU5RHFBV25xZENkSlF3MGhaZklERzJMaHZ4K0x0dGlncUpDMDFWblFicGkvUkhtUWl1VkFvR0FiMDZWXG42d3BVTHIvZlc5TFhsZytKaUM5ZzZpYzI4dCtxbmI0SkFHWmlXTTE5QjlkR21lb3pRaG5FeFpoWXJKNmJJeW5aXG4zQi84dXN2VUI2NkZMeXVIa1NQa2RjVUt3azg5UmlycHcyVjFZck5odTBwdTExSGR1ZmFkaGU3eHl5RVJqWXRFXG4xTUU3M2RDQlYwcFFkb1NqU0dpOGRRTHRXNVBkWWMwUVMrd252Uk1DZ1lFQW5wS2pPZC9ZUmRsS2U5SnM4MWh3XG5XT3B1NURwdGMrdzVOdGMvd2lFbkZ6cXV5b25ud21VSGd1K2hZaHJwZnNpaExGM1hHaTViaGRZN1pVVDlpbTR1XG5keWhoM3U0Ump1ZHlmVHh1eWZ6QXFTMTJpMEVHTnB6YVVXRldjdmMyTnBPbk15MG4wWDBNNXZFVk9xeTRnVnZTXG5tZXpnaDZESEMwWVRhcXozY2FUWTF3OD1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmbG93YWdlbnQtc3luY0BmbG93YWdlbnQtdjMtc3luYy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTMxOTIwMTI2ODQ4NzQ5Njk1NjQiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2Zsb3dhZ2VudC1zeW5jJTQwZmxvd2FnZW50LXYzLXN5bmMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
        sync: false













