services:
  - type: web
    name: flowagent-v3-gdrive-sync
    plan: free
    region: frankfurt
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_FOLDER_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: POLL_SECONDS
        sync: false
      - key: BEARER_TOKEN
        sync: false
      - key: OCR_ENABLED
        value: "1"


