services:
  - type: web
    name: flowagent-v3-gdrive-sync
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_FOLDER_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: POLL_SECONDS
        sync: false
